
language: cpp

os:
  - linux

sudo: required

dist: trusty

compiler:
  - gcc
  - clang

env:
  global:
    - CI_HOME=`pwd`
  matrix:
    - LIBCMAES=ON NLOPT=ON TBB=ON EXPERIMENTAL=OFF SFERES=OFF
    - LIBCMAES=ON NLOPT=ON TBB=OFF EXPERIMENTAL=OFF SFERES=OFF
    - LIBCMAES=ON NLOPT=OFF TBB=ON EXPERIMENTAL=OFF SFERES=OFF
    - LIBCMAES=ON NLOPT=OFF TBB=OFF EXPERIMENTAL=OFF SFERES=OFF
    - LIBCMAES=OFF NLOPT=ON TBB=ON EXPERIMENTAL=OFF SFERES=OFF
    - LIBCMAES=OFF NLOPT=ON TBB=OFF EXPERIMENTAL=OFF SFERES=OFF
    - LIBCMAES=OFF NLOPT=OFF TBB=ON EXPERIMENTAL=OFF SFERES=OFF
    - LIBCMAES=OFF NLOPT=OFF TBB=OFF EXPERIMENTAL=OFF SFERES=OFF
    - LIBCMAES=ON NLOPT=OFF TBB=OFF EXPERIMENTAL=ON SFERES=OFF
    - LIBCMAES=OFF NLOPT=OFF TBB=OFF EXPERIMENTAL=ON SFERES=OFF
    - LIBCMAES=ON NLOPT=OFF TBB=ON EXPERIMENTAL=ON SFERES=OFF
    - LIBCMAES=OFF NLOPT=OFF TBB=ON EXPERIMENTAL=ON SFERES=OFF
    - LIBCMAES=ON NLOPT=OFF TBB=OFF EXPERIMENTAL=ON SFERES=ON
    - LIBCMAES=OFF NLOPT=OFF TBB=OFF EXPERIMENTAL=ON SFERES=ON
    - LIBCMAES=ON NLOPT=OFF TBB=ON EXPERIMENTAL=ON SFERES=ON
    - LIBCMAES=OFF NLOPT=OFF TBB=ON EXPERIMENTAL=ON SFERES=ON

addons:
  apt:
    packages:
    - libboost1.55-all-dev
    - libeigen3-dev

install:
  - if [ "$LIBCMAES" = "ON" ]; then 'ci/install_libcmaes.sh' ; fi
  - if [ "$NLOPT" = "ON" ]; then 'ci/install_nlopt.sh' ; fi
  - if [ "$TBB" = "ON" ]; then 'ci/install_tbb.sh' ; fi
  - if [ "$SFERES" = "ON" ]; then 'ci/install_sferes.sh' ; fi


# Change this to your needs
script:
  - if [ "$SFERES" = "OFF" ]; ./waf configure ; else ./waf configure --sferes=$SFERES_HOME ; fi
  - if [ "$EXPERIMENTAL" = "OFF" ]; then ./waf --tests --alltests -v ; else ./waf --experimental ; fi
